In [48]:
# autograd
import torch as t
# create a tensor and set requires_grad = True
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [16]:
y = x+2
print(y)
print(y.grad_fn)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [17]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [18]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [19]:
# Gradients
out.backward()
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [57]:
x = torch.randn(3,requires_grad=True)
print(x)
y = x*2
i = 1
# y.data.norm() 二范数
while y.data.norm()<1000:
    print("第%d次循环" % i)
    print(y)
    
    print(y.data.norm())
    i += 1
    y = y*2
    
print(y)

tensor([ 0.2276, -0.8109, -0.4417])
第1次循环
tensor([ 0.4551, -1.6219, -0.8833])
tensor(1.9021)
第2次循环
tensor([ 0.9103, -3.2437, -1.7666])
tensor(3.8041)
第3次循环
tensor([ 1.8205, -6.4875, -3.5332])
tensor(7.6082)
第4次循环
tensor([  3.6411, -12.9749,  -7.0664])
tensor(15.2164)
第5次循环
tensor([  7.2821, -25.9498, -14.1328])
tensor(30.4329)
第6次循环
tensor([ 14.5642, -51.8997, -28.2656])
tensor(60.8657)
第7次循环
tensor([  29.1285, -103.7994,  -56.5312])
tensor(121.7315)
第8次循环
tensor([  58.2570, -207.5987, -113.0624])
tensor(243.4630)
第9次循环
tensor([ 116.5140, -415.1974, -226.1249])
tensor(486.9260)
第10次循环
tensor([ 233.0279, -830.3949, -452.2498])
tensor(973.8519)
tensor([  466.0558, -1660.7898,  -904.4995])


In [23]:
from torch.autograd import Variable


In [49]:
# 使tensor新建一个Variable
x = Variable(t.ones(2,2),requires_grad=True)
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [37]:
y = x.sum()
print(y)
print(y.grad_fn)

tensor(4.)


In [40]:
# 反向传播计算梯度
y.backward()
print(x.grad)
# 梯度累计，每次求梯度之前都需要清除
x.grad.data.zero_()

tensor([[ 1.,  1.],
        [ 1.,  1.]])


tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [54]:
import torch as t
x = Variable(t.ones(4,5))
y = t.cos(x)
x_tensor_cos = t.cos(x.data)
print(y)
x_tensor_cos

tensor([[ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
        [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
        [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
        [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403]])


tensor([[ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
        [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
        [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
        [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403]])