In [1]:
from __future__ import print_function
import torch

In [2]:
# 创建5*3矩阵 无初始化
x = torch.empty(5, 3)
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5,3,dtype = torch.long)
# Construct a tensor directly from data:
x = torch.tensor([5.5,3])

# new_* methods take in sizes
x = x.new_ones(5, 3, dtype=torch.double)
# override dtype! result has the same size
x = torch.randn_like(x, dtype=torch.float)
# Get its size: 输出为元组（[5，3])
print(x.size())

torch.Size([5, 3])


In [4]:
# operation

In [5]:
# index
print(x[:, 1])

tensor([ 1.0293, -1.0297, -0.1682,  1.7137, -1.6072])


In [6]:
# add
y = torch.rand(5,3)
print(x+y) # 等效
print(torch.add(x, y)) # 等效
result = torch.empty(5, 3) # 等效
torch.add(x, y, out=result)
print(result)
y.add_(x) # adds x to y
print(y)


tensor([[-1.1005,  1.4233,  0.1836],
        [-0.7311, -0.1118, -0.2775],
        [ 0.9153,  0.1554,  1.1164],
        [ 0.1111,  2.3172,  0.3252],
        [ 0.1114, -0.9509, -1.7234]])
tensor([[-1.1005,  1.4233,  0.1836],
        [-0.7311, -0.1118, -0.2775],
        [ 0.9153,  0.1554,  1.1164],
        [ 0.1111,  2.3172,  0.3252],
        [ 0.1114, -0.9509, -1.7234]])
tensor([[-1.1005,  1.4233,  0.1836],
        [-0.7311, -0.1118, -0.2775],
        [ 0.9153,  0.1554,  1.1164],
        [ 0.1111,  2.3172,  0.3252],
        [ 0.1114, -0.9509, -1.7234]])
tensor([[-1.1005,  1.4233,  0.1836],
        [-0.7311, -0.1118, -0.2775],
        [ 0.9153,  0.1554,  1.1164],
        [ 0.1111,  2.3172,  0.3252],
        [ 0.1114, -0.9509, -1.7234]])


In [9]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([ 0.3763])
0.37628257274627686


In [12]:
# NumPy Bridge

In [18]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)
a = a+1
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]
tensor([ 3.,  3.,  3.,  3.,  3.])
[2. 2. 2. 2. 2.]


In [20]:
# convert numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
