In [1]:
import torch 
a = torch.arange(0,6)
a.view(2,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])

In [2]:
b = a.view(-1,3)

In [3]:
# 不明白有什么用
b.unsqueeze(1).size()

torch.Size([2, 1, 3])

In [4]:
b.unsqueeze(-2).size()

torch.Size([2, 1, 3])

In [5]:
a = torch.randn(3,4)
print(a)
a[a>1]

tensor([[ 0.6282, -0.2018, -0.0749,  0.3770],
        [ 1.4723,  0.6232, -0.9976,  0.5319],
        [-0.6578, -0.5965, -0.4678,  0.6883]])


tensor([ 1.4723])

In [6]:
a[torch.LongTensor([0,1])]

tensor([[ 0.6282, -0.2018, -0.0749,  0.3770],
        [ 1.4723,  0.6232, -0.9976,  0.5319]])

In [12]:
a = torch.randn(4,5)
print(a)
torch.mean(a,1)

tensor([[ 0.7970,  0.1684, -0.1503,  0.4470,  1.4540],
        [-1.0418,  0.8789, -0.2061,  1.0514, -1.9135],
        [-0.5068, -0.8532, -0.8538, -0.0585,  1.0105],
        [ 0.6111, -0.3653, -0.5761, -0.0598,  0.0929]])


tensor([ 0.5432, -0.2462, -0.2524, -0.0594])

In [16]:
torch.median(a,0)

(tensor([-0.5068, -0.3653, -0.5761, -0.0585,  0.0929]),
 tensor([ 2,  3,  3,  2,  3]))

In [20]:
a = torch.randn(4,3)
print(a)
torch.norm(a,2,1)

tensor([[ 0.7320, -1.0116,  0.1908],
        [ 1.2622, -0.4524,  1.3088],
        [ 0.8373,  0.5420,  0.0125],
        [ 0.7570,  0.9295,  0.2243]])


tensor([ 1.2632,  1.8737,  0.9975,  1.2195])