In [9]:
import torch 
a = torch.arange(0,6)
a.view(2,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])

In [18]:
b = a.view(-1,3)

In [19]:
# 不明白有什么用
b.unsqueeze(1).size()

torch.Size([2, 1, 3])

In [20]:
b.unsqueeze(-2).size()

torch.Size([2, 1, 3])

In [30]:
a = torch.randn(3,4)
print(a)
a[a>1]

tensor([[ 0.9273,  0.3349,  0.2275,  1.0977],
        [-2.1313, -0.1252,  1.5708,  0.1493],
        [ 2.3479, -0.2397,  0.0442,  0.4979]])


tensor([ 1.0977,  1.5708,  2.3479])

In [31]:
a[torch.LongTensor([0,1])]

tensor([[ 0.9273,  0.3349,  0.2275,  1.0977],
        [-2.1313, -0.1252,  1.5708,  0.1493]])